# Generated by Django 5.1.4 on 2026-10-01 16:51

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosticTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "diagnostic test",
                "verbose_name_plural": "diagnostic tests",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="diagnostics_is_acti_6e371a_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_lower_diagnostic_test_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CentreTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="centre_tests",
                        to="diagnostics.diagnosticcentre",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_in_centres",
                        to="diagnostics.diagnostictest",
                    ),
                ),
            ],
            options={
                "verbose_name": "centre test",
                "verbose_name_plural": "centre tests",
                "ordering": ["centre", "test"],
                "indexes": [
                    models.Index(
                        fields=["centre", "is_available"],
                        name="diagnostics_centre__1d2280_idx",
                    ),
                    models.Index(
                        fields=["test", "is_available"],
                        name="diagnostics_test_id_3a39f3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("centre", "test"), name="unique_centre_diagnostic_test"
                    )
                ],
            },
        ),
    ]
