# Generated by Django 5.1.4 on 2026-10-01 17:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0002_diagnostictest_centretest"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "centre_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="diagnostics.centretest",
                    ),
                ),
            ],
            options={
                "verbose_name": "appointment slot",
                "verbose_name_plural": "appointment slots",
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["centre_test", "date"],
                        name="diagnostics_centre__28a277_idx",
                    ),
                    models.Index(
                        fields=["date", "start_time"],
                        name="diagnostics_date_00bf6e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("centre_test", "date", "start_time", "end_time"),
                        name="unique_centre_test_slot",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("capacity__gte", 1)),
                        name="chk_slot_capacity_gte_1",
                    ),
                ],
            },
        ),
    ]
