# Generated by Django 5.1.4 on 2026-10-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(default="PROCESSED", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "webhook event",
                "verbose_name_plural": "webhook events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_id"], name="payments_we_event_i_aaa1d5_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="payments_we_event_t_9f7fa1_idx"
                    ),
                ],
            },
        ),
    ]
