# Generated by Django 5.1.4 on 2026-10-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_webhookevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webhookevent",
            name="status",
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="transaction_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["transaction_id"], name="payments_we_transac_6c54d0_idx"
            ),
        ),
    ]
